-- 3. QUERY CREATION

-- 3.1 SLIDE 1 (ANSWER Q1 AND Q2)
;
CREATE VIEW TOP_FIVE_Q1 
AS
	SELECT SEASON, LEAGUE, TEAM, GOALS_IN_FAVOR, GOALS_AGAINST, POINTS, GAMES, WON, TIE, LOST, PRCNT_WON, PRCNT_TIE, PRCNT_LOST, [RANK] FROM [dbo].[TOP_FIVE] 
	WHERE LEAGUE NOT IN ('UEFA Champions League','UEFA Europa Conference League','UEFA Europa League')
GO
;

CREATE VIEW WORST_FIVE_Q1 
AS
SELECT SEASON, LEAGUE, TEAM, GOALS_IN_FAVOR, GOALS_AGAINST, POINTS, GAMES, WON, TIE, LOST, PRCNT_WON, PRCNT_TIE, PRCNT_LOST, [RANK] FROM [dbo].[WORST_FIVE] 
WHERE LEAGUE NOT IN ('UEFA Champions League','UEFA Europa Conference League','UEFA Europa League')
GO
;

-- 3.2 SLIDE 2 (ANSWER Q3)

CREATE VIEW COMPETITIVENESS_LEAGUES_Q3
AS
SELECT A.SEASON, A.LEAGUE, NUMBER_TEAMS, GAMES_PER_TEAM, AVG_PRCNT_WON, AVG_PRCNT_TIE, AVG_PRCNT_LOST, STDEV_PRCNT_WON, STDEV_PRCNT_TIE, STDEV_PRCNT_LOST, RANK_1
	   , A.MIN_PRCNT_WON, A.MAX_PRCNT_WON
	   , B.P25_PRCNT_WON, B.P50_PRCNT_WON, B.P75_PRCNT_WON
FROM [dbo].[COMPETITIVENESS_LEAGUES] AS A LEFT JOIN [dbo].[PERCENTILES_LEAGUE] AS B ON A.LEAGUE = B.LEAGUE
WHERE A.LEAGUE NOT IN ('UEFA Champions League','UEFA Europa Conference League','UEFA Europa League')
GO
;

-- 3.3. SLIDE 3 (ANSWER Q4)

-- PART 1 - WORST PERFORMERS IN  THE BEST LEAGUE VS WORST LEAGUE
SELECT SEASON, LEAGUE, TEAM, POINTS, GAMES, RANK_1, ADDED 
FROM [dbo].[WORST_PERFORMERS_BEST_LEAGUE]

-- PART 2 - BEST PERFORMERS IN THE WORST LEAGUE VS BEST LEAGUE
SELECT SEASON, LEAGUE, TEAM, POINTS, GAMES, RANK_1, ADDED 
FROM [dbo].[BEST_PERFORMERS_WORST_LEAGUE]

-- 4. END.